name: Runner Performance Test

on:
  workflow_dispatch:

jobs:
  performance_test:
    runs-on: self-hosted
    steps:
      - name: Print System Info
        run: |
          echo "CPU Info:"
          lscpu || sysctl -a | grep machdep.cpu
          echo "Memory Info:"
          free -h || vm_stat
          echo "Disk Usage:"
          df -h

      - name: Install Dependencies
        run: |
          echo "Installing required packages..."
          command -v apt-get && apt-get update && apt-get install -y stress speedtest-cli || echo "Skipping installation"

      - name: Stress Test CPU
        run: |
          echo "Starting CPU stress test..."
          command -v stress && stress --cpu 4 --timeout 600s || echo "Stress test skipped"

      - name: Memory Stress Test
        run: |
          echo "Starting Memory stress test..."
          command -v stress && stress --vm 2 --vm-bytes 512M --timeout 600s || echo "Memory test skipped"

      - name: Disk Speed Test
        run: |
          echo "Testing Disk Write Speed..."
          dd if=/dev/zero of=tempfile bs=1M count=1024 conv=fdatasync
          rm tempfile

      - name: Network Speed Test
        run: |
          echo "Testing Network Speed..."
          command -v speedtest-cli && speedtest-cli --simple || echo "Speed test skipped"
